export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const SET_ALERT = 'SET_ALERT'
export const DELETE_ALERT = 'DELETE_ALERT'
export const DELETE_ALL_ALERT = 'DELETE_ALL_ALERT'
export const ADMIN_LOADED = 'ADMIN_LOADED'
export const AUTH_FAIL = 'AUTH_FAIL'
export const LOGOUT = 'LOGOUT'

// GET_SETTINGS, SETTINGS_FAIL
export const GET_SETTINGS = 'GET_SETTINGS'
export const SETTINGS_FAIL = 'SETTINGS_FAIL '

// faq
export const FAQ_FAIL = 'FAQ_FAIL'
export const GET_ALL_FAQ = 'GET_ALL_FAQ'

export const GET_ALL_CMS = 'GET_ALL_CMS'
export const GET_ALL_MEDIA = 'GET_ALL_MEDIA'
export const GET_ALL_NEWS = 'GET_ALL_NEWS'

export const GET_ALL_GIFT = 'GET_ALL_GIFT'

export const GET_ALL_HISTORY = 'GET_ALL_HISTORY'
export const GET_ALL_LEAVE_REQUEST = 'GET_ALL_LEAVE_REQUEST'

export const GET_COACH_SALARY = 'GET_COACH_SALARY'

export const GET_NOTIFICATION_LIST = 'GET_NOTIFICATION_LIST'
export const NOTIFICATION_LOADING = 'NOTIFICATION_LOADING'
export const GET_REMARKS = 'GET_REMARKS'

// Company Profile
export const COMPANY_PROFILE = 'COMPANY_PROFILE'
export const COMPANY_DETAILS = 'COMPANY_DETAILS'
export const COMPANY_POSTS = 'COMPANY_POSTS'
export const COMPANY_CHARGING = 'COMPANY_CHARGING'

export const STATE_NAME = 'STATE_NAME'
export const CITY_NAME = 'CITY_NAME'
// Vehicle
export const VEHICLE_LIST = 'VEHICLE_LIST'
export const VEHICLE_DETAILS = 'VEHICLE_DETAILS'
export const VEHICLE_VIDEOS = 'VEHICLE_VIDEOS'

//user
export const USER_LIST = 'USER_LIST'
export const USER_DETAILS = 'USER_DETAILS'
export const USER_TIPS = 'USER_TIPS'
export const COMMUNITY_FORUM = 'COMMUNITY_FORUM'

export const CITIES_LIST = 'CITIES_LIST'
export const STATE_LIST = 'STATE_LIST'

export const CONSULTANT_PAYMENT = 'CONSULTANT_PAYMENT'
export const USER_SUBSCRIBE_LIST = 'USER_SUBSCRIBE_LIST'
export const CONSULTANT_TIP_LIST = 'CONSULTANT_TIP_LIST'
export const CONSULTANT_MEMBER_LIST = 'CONSULTANT_MEMBER_LIST'
export const GET_ALL_PAYMENT_INTIMATE = 'GET_ALL_PAYMENT_INTIMATE'
export const GET_SUBSCRIBE_LIST_ALL = 'GET_SUBSCRIBE_LIST_ALL'
